<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{a) Introduction}
-->

Introduction
========================================================

### What is a Choropleth?

A choropleth is a map which: 

  1. Shows geographic boundaries.
  2. Colors those regions based on some metric.

Choropleths are useful for visualizing data where geographic boundaries are a natural unit of aggregation.  For example, here is a choropleth that shows 2012 US State Population Estimates:

```{r message=FALSE}
    library(choroplethr)

    data(df_pop_state)
    state_choropleth(df_pop_state, 
                     title  = "2012 US State Population Estimates", 
                     legend = "Population")
```

### What is choroplethr? 

`choroplethr` is an R package that facilitates the creation of choropleth maps in R. It does this in 3 ways:

1. It provides ready-made functions for creating choropleths using the most common geographic boundaries (US States, US Counties, Countries of the world, and Administrative Level 1 maps of every country of the world).
2. It provides a framework for creating choropleths from arbitrary shapefiles.
3. It provides API connections to interesting data sources for making choropleths.

The remaining vignettes demonstrate basic usage of `choroplethr`. To learn more, please visit the choroplethr [website](https://arilamstein.com/open-source/). 
